-- ############################################################################
-- 🛑  DANGEROUS / STAGED MIGRATION — DO NOT RUN CASUALLY  🛑
-- ############################################################################
-- Purpose: unlock multi-tenant ONBOARDING (Create Workspace + Custom Domains +
-- per-tenant profiles + RLS isolation) on the SAME Supabase project, after
-- Sections A + B are already applied in production.
--
-- Prerequisites (must all be true before running):
--   * Sections A + B applied; every existing row already has a non-null tenant_id.
--   * A FULL database backup exists (this drops a constraint + changes a PK default).
--   * The app no longer writes upsert({id:1}) in any active path — TRUE as of the
--     tenant-aware admin (commit that added loadProfile/persistProfile).
--
-- Run it in the numbered order below, verifying after each part. Parts 1–2 are the
-- irreversible Section C core; part 3 opens the onboarding write paths; part 4 makes
-- tenant_admins readable by the admin app.
--
-- ⚠️  Reversible only via the backup. Verify Part 1–2 on a DUMMY tenant first.
-- ############################################################################


-- ============================================================================
-- PART 1 — Remove the single-profile lock and make profile.id auto-generate.
--   Without this a second tenant's profile row cannot exist (Create Tenant fails).
-- ============================================================================
ALTER TABLE profile DROP CONSTRAINT IF EXISTS single_profile;
ALTER TABLE profile ALTER COLUMN id DROP DEFAULT;
-- Keep the existing id = 1 row; new rows auto-assign id = 2, 3, ... so the app can
-- INSERT a profile without supplying an id.
ALTER TABLE profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 2);
-- One profile per tenant (the new effective key).
ALTER TABLE profile ADD CONSTRAINT uq_profile_tenant UNIQUE (tenant_id);


-- ============================================================================
-- PART 2 — Enforce tenant ownership (rejects null tenant_id going forward).
--   Only run once you've confirmed NO row has a null tenant_id (Section B backfill).
--   Check first:
--     SELECT count(*) FROM profile          WHERE tenant_id IS NULL;  -- expect 0
--     SELECT count(*) FROM projects         WHERE tenant_id IS NULL;  -- expect 0
--     SELECT count(*) FROM analytics_events WHERE tenant_id IS NULL;  -- expect 0
-- ============================================================================
ALTER TABLE profile          ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE projects         ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE analytics_events ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE profile          ADD CONSTRAINT fk_profile_tenant   FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE projects         ADD CONSTRAINT fk_projects_tenant  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE analytics_events ADD CONSTRAINT fk_analytics_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;


-- ============================================================================
-- PART 3 — RLS + write policies so admins manage ONLY tenants they own, and the
--   onboarding UI (Create Workspace + Domains) can write.
--
--   Strategy: ADD the new tenant-scoped policies FIRST, VERIFY on a dummy tenant,
--   THEN drop the old un-scoped is_admin() policies (bottom of this part).
-- ============================================================================

-- 3a. Per-tenant data isolation (replaces the un-scoped is_admin() writes).
CREATE POLICY "Tenant admins write profile"  ON profile          FOR ALL    TO authenticated USING (is_tenant_admin(tenant_id)) WITH CHECK (is_tenant_admin(tenant_id));
CREATE POLICY "Tenant admins write projects" ON projects         FOR ALL    TO authenticated USING (is_tenant_admin(tenant_id)) WITH CHECK (is_tenant_admin(tenant_id));
CREATE POLICY "Tenant admins read events"    ON analytics_events FOR SELECT TO authenticated USING (is_tenant_admin(tenant_id));

-- 3b. Onboarding: allow an authenticated admin to create a tenant, and to own the
--     row they just created. (tenants currently has only a public-read policy.)
--     "create then self-own" — a tenant is creatable by any signed-in admin; its
--     domains/data are then gated by is_tenant_admin() above.
GRANT INSERT, UPDATE ON tenants        TO authenticated;
GRANT INSERT, UPDATE, DELETE ON tenant_admins  TO authenticated;
GRANT SELECT ON tenant_admins TO authenticated;
GRANT INSERT, UPDATE, DELETE ON tenant_domains TO authenticated;

DROP POLICY IF EXISTS "Admins create tenants" ON tenants;
CREATE POLICY "Admins create tenants" ON tenants
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM admin_usernames WHERE user_id = auth.uid()));
DROP POLICY IF EXISTS "Tenant admins update tenant" ON tenants;
CREATE POLICY "Tenant admins update tenant" ON tenants
  FOR UPDATE TO authenticated USING (is_tenant_admin(id)) WITH CHECK (is_tenant_admin(id));

-- 3c. tenant_admins: an admin may read their own mappings and create the owner row
--     for a tenant they just created (self-assignment only).
ALTER TABLE tenant_admins ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins read own tenant mappings" ON tenant_admins;
CREATE POLICY "Admins read own tenant mappings" ON tenant_admins
  FOR SELECT TO authenticated USING (user_id = auth.uid());
DROP POLICY IF EXISTS "Admins self-assign new tenant" ON tenant_admins;
CREATE POLICY "Admins self-assign new tenant" ON tenant_admins
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());

-- 3d. tenant_domains: only a tenant's admins may add/remove its domains. Public read
--     already exists from Section A (needed by the resolver).
DROP POLICY IF EXISTS "Tenant admins manage domains" ON tenant_domains;
CREATE POLICY "Tenant admins manage domains" ON tenant_domains
  FOR ALL TO authenticated USING (is_tenant_admin(tenant_id)) WITH CHECK (is_tenant_admin(tenant_id));

-- 3e. Assign a CLIENT as admin of a tenant you already administer (the "assign a
--     client admin" onboarding step; called by the admin UI via supabase.rpc()).
--     SECURITY DEFINER so it can resolve username -> user_id and insert the mapping
--     WITHOUT exposing admin_usernames or other users' mappings to the browser
--     (tenant_admins stays readable only for your own rows, per 3c).
CREATE OR REPLACE FUNCTION assign_tenant_admin(p_tenant_id UUID, p_username TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user UUID;
BEGIN
  -- the caller must already administer this tenant
  IF NOT is_tenant_admin(p_tenant_id) THEN
    RAISE EXCEPTION 'not an admin of this tenant';
  END IF;
  SELECT user_id INTO v_user FROM admin_usernames WHERE username = p_username;
  IF v_user IS NULL THEN
    RAISE EXCEPTION 'no user with that username';
  END IF;
  INSERT INTO tenant_admins (tenant_id, user_id, role)
  VALUES (p_tenant_id, v_user, 'owner')
  ON CONFLICT (tenant_id, user_id) DO NOTHING;
END;
$$;
GRANT EXECUTE ON FUNCTION assign_tenant_admin(UUID, TEXT) TO authenticated;

-- 3f. Storage: (OPTIONAL hardening) once uploads live under `t-<id>/`, you may scope
--     media writes per tenant by parsing the path prefix. Not required at launch —
--     images are public portfolio assets. Left commented on purpose.
-- (see storage.objects policies in supabase-complete.sql)

-- 3g. ONLY AFTER verifying 3a on a dummy tenant, drop the old un-scoped policies:
-- DROP POLICY IF EXISTS "Admins can write profile"  ON profile;
-- DROP POLICY IF EXISTS "Admins can write projects" ON projects;
-- DROP POLICY IF EXISTS "Admins can read events"    ON analytics_events;


-- ============================================================================
-- PART 4 — Verification (run, expect the noted results)
-- ============================================================================
-- new tenant profile can be created (as the app does): should succeed after Part 1
--   INSERT INTO tenants (slug, name) VALUES ('dummy-verify', 'Dummy') RETURNING id;
--   INSERT INTO profile (tenant_id, default_lang) VALUES ('<that id>', 'ar');  -- id auto-assigns
-- isolation: a second admin must NOT see/edit tenant #1's rows once 3f is done.
-- selector: SELECT grantee, privilege_type FROM information_schema.role_table_grants
--           WHERE table_name IN ('tenant_admins','tenants','tenant_domains') AND grantee='authenticated';

-- ============================================================================
-- PART 5 — PER-CLIENT ONBOARDING (manual steps that cannot be done from the app)
-- ============================================================================
-- Creating an auth user requires the Supabase dashboard or the admin API (service
-- role). The browser client cannot do it, and we deliberately do NOT ship a service
-- key to the front end. So for each new client, once per client:
--
--   1) Supabase Dashboard -> Authentication -> Users -> "Add user"
--      (email + password; send them the credentials or a reset link).
--
--   2) Give them a username so they can sign in (the /admin login resolves
--      username -> email via get_email_for_username). Replace the values:
--        INSERT INTO admin_usernames (username, user_id)
--        VALUES ('clientname', '<their auth user uuid>')
--        ON CONFLICT (username) DO NOTHING;
--
--   3) In /admin -> Account -> "Client admin", type that username and press Grant.
--      That calls assign_tenant_admin() (3e) and maps them to the selected tenant.
--
--   4) Custom domain: add the domain in /admin -> Account -> "Custom domains",
--      THEN add the same domain to the Vercel project and point DNS at Vercel.
--      Until DNS resolves, the client's portfolio is reachable at /<slug>.
--
-- NOTE: a client only needs an admin_usernames row to LOG IN. Their data access is
-- governed by tenant_admins + is_tenant_admin() (Part 3), so they can only ever
-- read/write their own tenant once 3g has been applied.

-- ############################################################################
-- 🛑  END — nothing above has been executed by the application. Run deliberately.
-- ############################################################################
