// A real PDF of the handoff credentials, written by hand.
//
// WHY BY HAND: the spec asked for "Download PDF" and the earlier build shipped a
// .txt instead, because a PDF library would break the five-runtime-dependency
// rule. A single-page PDF with a base-14 font is a small, well-specified text
// format though — catalog, pages, page, two font refs, one content stream, an
// xref table — so it is ~150 lines here rather than a dependency.
//
// WHAT IT CANNOT DO: base-14 Helvetica is WinAnsi-encoded, so it has no Arabic
// glyphs. Non-Latin-1 characters are stripped rather than rendered as garbage,
// and a value that survives as empty is dropped from the sheet entirely. In
// practice the fields that matter — username, password, URL, email — are always
// ASCII; only a workspace NAME can be Arabic, and it is the one field the client
// does not need in order to sign in. Callers that need Arabic should hand over
// the WhatsApp message or the clipboard text instead.

const PAGE_W = 595; // A4 at 72dpi
const PAGE_H = 842;
const MARGIN = 56;

// PDF strings are byte sequences; ( ) and \ are structural and must be escaped.
export function escapePdfText(s) {
  return String(s ?? '').replace(/([\\()])/g, '\\$1');
}

// Keep only what WinAnsi can actually draw. Newlines and tabs would break the
// one-line-per-Tj layout, so they collapse to spaces.
export function toLatin1(s) {
  const flat = String(s ?? '').replace(/[\r\n\t]+/g, ' ');
  let out = '';
  for (const ch of flat) {
    if (ch.codePointAt(0) < 256) out += ch;
  }
  return out.replace(/\s{2,}/g, ' ').trim();
}

// One row of the sheet, or null when nothing renderable survives sanitising.
function row(label, value) {
  const v = toLatin1(value);
  if (!v) return null;
  return { label: toLatin1(label), value: v };
}

function contentStream(creds, strings) {
  const rows = [
    row(strings.workspace, creds?.workspace),
    row(strings.portfolio, creds?.url),
    row(strings.signIn, creds?.signInUrl),
    row(strings.username, creds?.username),
    row(strings.password, creds?.password),
    row(strings.email, creds?.email),
  ].filter(Boolean);

  const ops = [];
  const text = (font, size, x, y, str, rgb) => {
    ops.push(`${rgb} rg`);
    ops.push('BT', `/${font} ${size} Tf`, `1 0 0 1 ${x} ${y} Tm`, `(${escapePdfText(str)}) Tj`, 'ET');
  };

  let y = PAGE_H - MARGIN - 12;
  text('F2', 20, MARGIN, y, strings.title, '0.05 0.06 0.09');
  y -= 22;
  text('F1', 10.5, MARGIN, y, strings.subtitle, '0.42 0.44 0.5');

  // rule under the header
  y -= 18;
  ops.push('0.85 0.86 0.9 rg', `${MARGIN} ${y} ${PAGE_W - MARGIN * 2} 0.8 re f`);

  y -= 34;
  for (const r of rows) {
    text('F1', 9, MARGIN, y, r.label.toUpperCase(), '0.45 0.47 0.53');
    y -= 17;
    text('F2', 13, MARGIN, y, r.value, '0.05 0.06 0.09');
    y -= 26;
  }

  // footer note, pinned to the bottom margin
  ops.push('0.85 0.86 0.9 rg', `${MARGIN} ${MARGIN + 34} ${PAGE_W - MARGIN * 2} 0.8 re f`);
  text('F1', 9, MARGIN, MARGIN + 18, strings.note, '0.45 0.47 0.53');

  return ops.join('\n');
}

const EN = {
  title: 'Your portfolio login',
  subtitle: 'Keep this somewhere safe. The password must be changed on first sign-in.',
  workspace: 'Workspace',
  portfolio: 'Portfolio',
  signIn: 'Sign in',
  username: 'Username',
  password: 'Temporary password',
  email: 'Email',
  note: 'Generated by Designakum. If you did not expect this document, ignore it.',
};

// The sheet is English-only by necessity — see the note at the top of the file.
export function buildCredentialsPdf(creds, strings = EN) {
  const s = { ...EN, ...strings };
  const stream = contentStream(creds, s);

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_W} ${PAGE_H}] ` +
      '/Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>',
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
  ];

  // Assemble, recording the byte offset of every object for the xref table.
  let pdf = '%PDF-1.4\n';
  const offsets = [];
  objects.forEach((body, i) => {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
  });

  const xrefStart = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const off of offsets) {
    pdf += `${String(off).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`;

  // One byte per character. Everything above is Latin-1 by construction, so the
  // string length used for the xref offsets IS the byte length — encoding this
  // as UTF-8 would silently shift every offset and corrupt the file.
  const bytes = new Uint8Array(pdf.length);
  for (let i = 0; i < pdf.length; i += 1) bytes[i] = pdf.charCodeAt(i) & 0xff;
  return bytes;
}

export default buildCredentialsPdf;
